### ISSUE TITLE
feature - add widget `StatesBuilder`

### ISSUE THREAD

**Issue by beeth0ven** [LoveCommunity/flutter_scope#18]
subtask of #9 :
- [x] add widget `StatesBuilder.statesEqual` #19
- [x] add `StatesBuilder.default` #25 
- [x] add widget `StatesBuilderSelect` #28
