### ISSUE TITLE
feature - add `FlutterScope` addon methods

### ISSUE THREAD

**Issue by beeth0ven** [LoveCommunity/flutter_scope#20]
- [x] add method `FlutterScope.of` #21
- [x] add method `context.scopeOrNull` #22
- [x] add method `context.scope` #23
