### ISSUE TITLE
feature - add widget `StatesListener`

### ISSUE THREAD

**Issue by beeth0ven** [LoveCommunity/flutter_scope#30]
subtask of #9 :

- [x] add widget `StatesListener.statesEqual` #31 
- [x] add `StatesListener.default` #32
- [x] add widget `StatesListenerSelect` #33
