### ISSUE TITLE
plan for version 0.1.0-alpha.1

### ISSUE THREAD

**Issue by beeth0ven** [LoveCommunity/flutter_scope#9]
features:
- [x] add configurable `FinalChangeNotifier` #2 
- [x] add configurable `FinalValueNotifier` #3 
- [x] add widget `FlutterScope` #10
- [x] add widget `StatesBuilder` #18
- [x] add widget `StatesListener` #30
